### ISSUE TITLE
Can't push resource

### ISSUE THREAD

**Issue by deimosfr** [transifex/transifex-client#71] opened 2014-08-30 12:49 UTC
Hi,

I'm trying to push sources on Transifex for a new and empty project, however I get this error with the latest beta version:

```
> tx --traceback push -s                                  
Pushing translations for resource MySecureShell.index:
Pushing source file (build/locale/index.pot)
Resource does not exist.  Creating...
Traceback (most recent call last):
  File "/usr/local/bin/tx", line 94, in main
    utils.exec_command(cmd, args[1:], path_to_tx)
  File "/usr/local/lib/python2.7/dist-packages/txclib/utils.py", line 182, in exec_command
    cmd_fn(*args,**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/txclib/commands.py", line 336, in cmd_push
    no_interactive=options.no_interactive
  File "/usr/local/lib/python2.7/dist-packages/txclib/project.py", line 606, in push
    self._create_resource(resource, project_slug, fileinfo, filename)
  File "/usr/local/lib/python2.7/dist-packages/txclib/project.py", line 1218, in _create_resource
    r, charset = make_request(method, hostname, url, username, passwd, data)
  File "/usr/local/lib/python2.7/dist-packages/txclib/utils.py", line 111, in make_request
    raise HttpNotFound(data)
HttpNotFound: Not Found

```

It doesn't work also with the previous beta and stable version. Any idea ?

Thanks

**Comment by bittner** [comment] 2015-09-24 14:11
Duplicate of #51. Try installing the development version, or the latest beta of the `transifex-client`.

**Comment by diegobz** [comment] 2015-11-06 21:37
Closing as explained in the comment above.

**Closed by diegobz** 2015-11-06 21:37 UTC
