### ISSUE TITLE
tx is duplicating a comment every time a translation changes

### ISSUE THREAD

**Issue by SamuAlfageme** [transifex/transifex-client#173] opened 2017-05-12 10:48 UTC
We have a bot that runs `tx` every night to update all the translation files on our project: https://github.com/owncloud/client and it has been running smooth and reliable for some time now. But we detected recently an issue on one `.desktop` file: https://github.com/owncloud/client/issues/5767 

Basically, every time a translation is included the `#Translations` comment is being duplicated on that file. Maybe you guys have a clue to avoid this from happening, thanks!

**Comment by nelefth** [comment] 2017-05-12 17:17
@SamuAlfageme I tried to reproduce this without any luck.

Here are the steps I followed:
#1: I uploaded a .desktop source file to Transifex
#2: I translated one target language and then pulled the source file via TX client.
The comment "# Translations" was included only once
#3: After that, I translated another target language and pulled the updated source file. 
Again, the behavior was the expected one. The comment appeared only once in the exported file.

![screen shot 2017-05-12 at 8 15 42 pm](https://cloud.githubusercontent.com/assets/13518557/26009051/dd3c91b2-374f-11e7-8d1c-5b9e74231703.png)

Could you please check the above steps and let me know if I am missing something regarding your case?

**Comment by SamuAlfageme** [comment] 2017-05-15 08:06
@nelefth thanks for your fast reply! Hm... only difference I can see between your steps and our repository is that the file is named `mirall.desktop.in` (with the `.in` there as suffix)

This is the first commit: https://github.com/owncloud/client/commit/8379a36a7504f3ee4d1204ec53e8314b1905d017 that introduced the duplicates. You can see that some translations were tagged as deleted by git but actually relocated inside the file. (This: https://github.com/owncloud/client/commit/8694db1c4995d12c15cf8a33455dfc7511e890c4 on the other side was the first time the tx-client was run in the repository). Maybe this can help us understand or reproduce the issue.

Is there a way to create a test project in transifex/reuse yours to try to reproduce this?

**Comment by nelefth** [comment] 2017-05-15 18:20
@SamuAlfageme thank you for your response. I was able to reproduce the behavior you are facing. 

Steps to reproduce: 

#1: Upload the file as a new resource in Transifex
#2: Translate a target language 
#3: Pull the source file
**Result**: The comment "Translations" is included only once.
#4: Use the generated file in order to update the source file (no modifications are needed to reproduce the issue)
#5: Once the file is updated, download it again from Transifex 
**Result**: the comment "Translations" is included twice in the generated file
If you translate another target language, download the source file and reupload it to Transifex as an updated source file version, then if you download it again the comment "Translations" will be included 3 times in the generated file. 
So, the issue is caused when you update your source file using the exported file.

Thank you for bringing this to our attention.

We will further investigate this behavior and properly handle this. 

In the meantime, I would suggest you update your source file without including the translations.

**Comment by nelefth** [comment] 2017-05-15 18:26
@SamuAlfageme since this behavior is not related to the tx Client tool but to the way our .desktop parser works, I will close the issue from here and add it to our backlog (not publicly accessible) for further handling. 

When the issue is resolved, I will let you know via email.

**Closed by nelefth** 2017-05-15 18:26 UTC

**Comment by SamuAlfageme** [comment] 2017-05-16 06:54
@nelefth Sure! 😉 Thanks a lot!

**Comment by guruz** [comment] 2019-02-04 12:40
Hi @nelefth .. Happy 2019 :)
Did you get any feedback on when this is put on your roadmap?
We're still getting the issue.. 
https://github.com/owncloud/client/commit/c9c4c9affe8234ee3630b8dec322238c8bd4405d
